### ISSUE TITLE
[Bug] ZLibrary crashes Discord when trying to show changelog

### ISSUE THREAD

**Issue by ezeholz** [rauenzi/BDPluginLibrary#159]
Everytime I update a plugin's version, ZLibrary throws a `Well, this is awkward` error.
![image](https://user-images.githubusercontent.com/30635862/196484370-e8b9255f-858a-4bb9-89fc-56854405564a.png)

In console, the error it's the following:
![image](https://user-images.githubusercontent.com/30635862/196484534-f081f2c5-7132-459b-aa15-452f43460fca.png)

To reproduce it, grab any plugin that uses ZLibrary, add `changelog: []` inside `config` object and change version.
You're gonna see the crash instead of the changelog window showing up.

**Comment by rauenzi** [comment]
This was fixed with 2.0.8, make sure your library is up to date!

**Comment by ezeholz** [comment]
I'm on version 2.0.8, and actually redownloaded from BD webpage just to be sure, but still the same error appears
![image](https://user-images.githubusercontent.com/30635862/196490728-48ec0780-f55e-4349-85e2-30fb141203f5.png)

**Comment by ezeholz** [comment]
Nevermind, 2.0.9 fixed it. BD plugin's webpage it's out of date. And there isn't a sign to update the library.
